basic:
    #!/usr/bin/bash
    export $(cat .env | grep -v '^#' | grep -v '^$' | xargs) && ./scripts/run_basic.sh

spike:
    #!/usr/bin/bash
    export $(cat .env | grep -v '^#' | grep -v '^$' | xargs) && ./scripts/run_spike.sh

stress:
    #!/usr/bin/bash
    export $(cat .env | grep -v '^#' | grep -v '^$' | xargs) && ./scripts/run_stress.sh

clean *args:
    #!/usr/bin/bash
    export $(cat .env | grep -v '^#' | grep -v '^$' | xargs) && python ./cleanup.py {{args}}