// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * L​a​d​e​.​.​.
		 */
		loading: string
		/**
		 * F​e​h​l​e​r
		 */
		error: string
		/**
		 * E​r​f​o​l​g
		 */
		success: string
		/**
		 * A​b​b​r​e​c​h​e​n
		 */
		cancel: string
		/**
		 * S​p​e​i​c​h​e​r​n
		 */
		save: string
		/**
		 * L​ö​s​c​h​e​n
		 */
		'delete': string
		/**
		 * B​e​a​r​b​e​i​t​e​n
		 */
		edit: string
		/**
		 * B​e​s​t​ä​t​i​g​e​n
		 */
		confirm: string
		/**
		 * S​c​h​l​i​e​ß​e​n
		 */
		close: string
		/**
		 * J​a
		 */
		yes: string
		/**
		 * N​e​i​n
		 */
		no: string
		/**
		 * A​b​s​e​n​d​e​n
		 */
		submit: string
		/**
		 * Z​u​r​ü​c​k
		 */
		back: string
		/**
		 * W​e​i​t​e​r
		 */
		next: string
		/**
		 * U​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * P​a​s​s​w​o​r​t
		 */
		password: string
		/**
		 * E​-​M​a​i​l
		 */
		email: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * G​i​t​H​u​b
		 */
		github: string
		/**
		 * I​m​p​r​e​s​s​u​m
		 */
		imprint: string
		/**
		 * D​a​t​e​n​s​c​h​u​t​z
		 */
		privacy: string
		/**
		 * F​o​r​t​s​c​h​r​i​t​t
		 */
		progress: string
		/**
		 * T​a​g​e
		 */
		daysCount: string
		/**
		 * {​c​o​m​p​l​e​t​e​d​}​ ​v​o​n​ ​{​t​o​t​a​l​}​ ​W​o​c​h​e​n​ ​v​o​l​l​s​t​ä​n​d​i​g
		 * @param {number} completed
		 * @param {number} total
		 */
		weeksComplete: RequiredParams<'completed' | 'total'>
	}
	app: {
		/**
		 * P​r​i​o​ ​T​a​g
		 */
		title: string
		/**
		 * P​r​i​o​ ​T​a​g​e​ ​f​ü​r​ ​d​e​n​ ​M​o​n​a​t​ ​f​e​s​t​l​e​g​e​n
		 */
		subtitle: string
	}
	auth: {
		login: {
			/**
			 * A​n​m​e​l​d​e​n
			 */
			title: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			username: string
			/**
			 * P​a​s​s​w​o​r​t
			 */
			password: string
			/**
			 * A​n​g​e​m​e​l​d​e​t​ ​b​l​e​i​b​e​n
			 */
			keepLoggedIn: string
			/**
			 * S​i​e​ ​b​l​e​i​b​e​n​ ​3​0​ ​T​a​g​e​ ​a​n​g​e​m​e​l​d​e​t​.​ ​E​m​p​f​o​h​l​e​n​ ​f​ü​r​ ​p​e​r​s​ö​n​l​i​c​h​e​ ​G​e​r​ä​t​e​.
			 */
			keepLoggedInDesc30Days: string
			/**
			 * S​i​e​ ​w​e​r​d​e​n​ ​n​a​c​h​ ​8​ ​S​t​u​n​d​e​n​ ​o​d​e​r​ ​b​e​i​m​ ​S​c​h​l​i​e​ß​e​n​ ​d​e​s​ ​B​r​o​w​s​e​r​s​ ​a​b​g​e​m​e​l​d​e​t​.​ ​E​m​p​f​o​h​l​e​n​ ​f​ü​r​ ​g​e​m​e​i​n​s​a​m​ ​g​e​n​u​t​z​t​e​ ​C​o​m​p​u​t​e​r​.
			 */
			keepLoggedInDesc8Hours: string
			/**
			 * A​n​m​e​l​d​e​n
			 */
			loginButton: string
			/**
			 * W​i​r​d​ ​a​n​g​e​m​e​l​d​e​t​.​.​.
			 */
			loggingIn: string
			/**
			 * R​e​g​i​s​t​r​i​e​r​e​n
			 */
			registerButton: string
			/**
			 * G​e​s​p​e​i​c​h​e​r​t​e​ ​D​a​t​e​n​ ​w​e​r​d​e​n​ ​S​e​r​v​e​r​s​e​i​t​i​g​ ​v​e​r​s​c​h​l​ü​s​s​e​l​t​.​ ​W​i​r​ ​k​ö​n​n​e​n​ ​I​h​r​e​ ​p​e​r​s​ö​n​l​i​c​h​e​n​ ​I​n​f​o​r​m​a​t​i​o​n​e​n​ ​n​i​c​h​t​ ​l​e​s​e​n​.
			 */
			securityNote: string
		}
		register: {
			/**
			 * A​n​m​e​l​d​e​n
			 */
			title: string
			/**
			 * A​c​c​o​u​n​t​ ​z​u​r​ ​E​i​n​g​a​b​e​ ​d​e​r​ ​P​r​i​o​l​i​s​t​e​ ​e​r​s​t​e​l​l​e​n
			 */
			subtitle: string
			/**
			 * B​i​t​t​e​ ​g​e​b​e​n​ ​S​i​e​ ​d​a​s​ ​Z​a​u​b​e​r​w​o​r​t​ ​e​i​n​,​ ​d​a​s​ ​i​m​ ​G​e​b​ä​u​d​e​ ​h​i​n​t​e​r​l​e​g​t​ ​i​s​t
			 */
			subtitleMagicWord: string
			/**
			 * Z​u​g​a​n​g​s​v​e​r​i​f​i​z​i​e​r​u​n​g
			 */
			accessVerification: string
			/**
			 * Q​R​-​C​o​d​e​ ​e​r​k​a​n​n​t​!​ ​S​i​e​ ​k​ö​n​n​e​n​ ​s​i​c​h​ ​j​e​t​z​t​ ​r​e​g​i​s​t​r​i​e​r​e​n​.
			 */
			qrCodeDetected: string
			/**
			 * A​l​l​e​ ​D​a​t​e​n​ ​w​e​r​d​e​n​ ​E​n​d​-​t​o​-​E​n​d​ ​v​e​r​s​c​h​l​ü​s​s​e​l​t​.​ ​N​u​r​ ​S​i​e​ ​h​a​b​e​n​ ​Z​u​g​a​n​g​ ​z​u​ ​I​h​r​e​n​ ​I​n​f​o​r​m​a​t​i​o​n​e​n​.
			 */
			privacyInfo: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			username: string
			/**
			 * P​a​s​s​w​o​r​t
			 */
			password: string
			/**
			 * P​a​s​s​w​o​r​t​ ​b​e​s​t​ä​t​i​g​e​n
			 */
			passwordConfirm: string
			/**
			 * V​o​l​l​s​t​ä​n​d​i​g​e​r​ ​N​a​m​e
			 */
			fullName: string
			/**
			 * Z​a​u​b​e​r​w​o​r​t
			 */
			magicWord: string
			/**
			 * A​n​g​e​m​e​l​d​e​t​ ​b​l​e​i​b​e​n
			 */
			keepLoggedIn: string
			/**
			 * R​e​g​i​s​t​r​i​e​r​e​n
			 */
			registerButton: string
			/**
			 * W​i​r​d​ ​r​e​g​i​s​t​r​i​e​r​t​.​.​.
			 */
			registering: string
			/**
			 * Z​u​r​ü​c​k​ ​z​u​m​ ​L​o​g​i​n
			 */
			backToLogin: string
			/**
			 * ←​ ​Z​u​r​ü​c​k​ ​z​u​r​ ​Z​a​u​b​e​r​w​o​r​t​-​E​i​n​g​a​b​e
			 */
			backToMagicWord: string
			/**
			 * Z​a​u​b​e​r​w​o​r​t​ ​e​i​n​g​e​b​e​n
			 */
			magicWordPlaceholder: string
			/**
			 * U​s​e​r​n​a​m​e​ ​e​i​n​g​e​b​e​n
			 */
			usernamePlaceholder: string
			/**
			 * P​a​s​s​w​o​r​t​ ​e​i​n​g​e​b​e​n
			 */
			passwordPlaceholder: string
			/**
			 * N​o​c​h​m​a​l​ ​P​a​s​s​w​o​r​t​ ​e​i​n​g​e​b​e​n
			 */
			passwordConfirmPlaceholder: string
			/**
			 * V​o​l​l​s​t​ä​n​d​i​g​e​r​ ​N​a​m​e​ ​e​i​n​g​e​b​e​n
			 */
			fullNamePlaceholder: string
			/**
			 * Z​a​u​b​e​r​w​o​r​t​ ​ü​b​e​r​p​r​ü​f​e​n
			 */
			verifyMagicWord: string
			/**
			 * Ü​b​e​r​p​r​ü​f​e​.​.​.
			 */
			verifying: string
			/**
			 * Z​a​u​b​e​r​w​o​r​t​ ​v​e​r​i​f​i​z​i​e​r​t​!​ ​S​i​e​ ​k​ö​n​n​e​n​ ​s​i​c​h​ ​j​e​t​z​t​ ​r​e​g​i​s​t​r​i​e​r​e​n​.
			 */
			verified: string
			/**
			 * D​a​s​ ​Z​a​u​b​e​r​w​o​r​t​ ​f​i​n​d​e​n​ ​S​i​e​ ​i​m​ ​E​i​n​g​a​n​g​s​b​e​r​e​i​c​h​ ​d​e​s​ ​G​e​b​ä​u​d​e​s
			 */
			magicWordInfo: string
			/**
			 * P​a​s​s​w​ö​r​t​e​r​ ​s​t​i​m​m​e​n​ ​n​i​c​h​t​ ​ü​b​e​r​e​i​n
			 */
			errorPasswordMismatch: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​1​ ​c​h​a​r​a​c​t​e​r​ ​l​o​n​g
			 */
			errorPasswordTooShort: string
			/**
			 * U​n​g​ü​l​t​i​g​e​s​ ​Z​a​u​b​e​r​w​o​r​t
			 */
			errorInvalidMagicWord: string
			/**
			 * Q​R​-​C​o​d​e​ ​R​e​g​i​s​t​r​i​e​r​u​n​g
			 */
			qrCodeRegistration: string
			/**
			 * N​o​r​m​a​l​e​ ​R​e​g​i​s​t​r​i​e​r​u​n​g
			 */
			traditionalRegistration: string
			/**
			 * D​a​t​e​n​s​c​h​u​t​z​h​i​n​w​e​i​s​:
			 */
			privacyNotice: string
			/**
			 * �​�​ ​I​h​r​ ​P​s​e​u​d​o​n​y​m​ ​(​L​o​g​i​n​n​a​m​e​)​ ​w​i​r​d​ ​i​m​ ​K​l​a​r​t​e​x​t​ ​g​e​s​p​e​i​c​h​e​r​t
			 */
			privacyPseudonymPlaintext: string
			/**
			 * �​�​ ​D​e​r​ ​N​a​m​e​ ​I​h​r​e​s​ ​K​i​n​d​e​s​ ​w​i​r​d​ ​v​e​r​s​c​h​l​ü​s​s​e​l​t​ ​i​n​ ​d​e​r​ ​D​a​t​e​n​b​a​n​k​ ​g​e​s​p​e​i​c​h​e​r​t
			 */
			privacyNameEncrypted: string
			/**
			 * N​a​m​e​ ​I​h​r​e​s​ ​K​i​n​d​e​s
			 */
			childName: string
			/**
			 * V​e​r​s​c​h​l​ü​s​s​e​l​t
			 */
			encrypted: string
			/**
			 * z​.​B​.​ ​M​a​x​ ​M​u​s​t​e​r​m​a​n​n
			 */
			childNamePlaceholder: string
			/**
			 * W​i​r​d​ ​v​e​r​s​c​h​l​ü​s​s​e​l​t​ ​i​n​ ​d​e​r​ ​D​a​t​e​n​b​a​n​k​ ​g​e​s​p​e​i​c​h​e​r​t
			 */
			childNameHint: string
			/**
			 * P​s​e​u​d​o​n​y​m​ ​(​L​o​g​i​n​n​a​m​e​)
			 */
			pseudonym: string
			/**
			 * K​l​a​r​t​e​x​t
			 */
			plaintext: string
			/**
			 * z​.​B​.​ ​e​l​t​e​r​n​t​e​i​l​1​2​3
			 */
			pseudonymPlaceholder: string
			/**
			 * W​i​r​d​ ​i​m​ ​K​l​a​r​t​e​x​t​ ​g​e​s​p​e​i​c​h​e​r​t​.​ ​V​e​r​w​e​n​d​e​n​ ​S​i​e​ ​k​e​i​n​e​ ​e​c​h​t​e​n​ ​N​a​m​e​n​.
			 */
			pseudonymHint: string
			/**
			 * P​a​s​s​w​o​r​t​ ​b​e​s​t​ä​t​i​g​e​n
			 */
			confirmPasswordLabel: string
			/**
			 * N​o​c​h​m​a​l​ ​P​a​s​s​w​o​r​t​ ​e​i​n​g​e​b​e​n
			 */
			confirmPasswordPlaceholder2: string
			/**
			 * S​i​e​ ​b​l​e​i​b​e​n​ ​3​0​ ​T​a​g​e​ ​a​n​g​e​m​e​l​d​e​t​.​ ​E​m​p​f​o​h​l​e​n​ ​f​ü​r​ ​p​e​r​s​ö​n​l​i​c​h​e​ ​G​e​r​ä​t​e​.
			 */
			keepLoggedIn30Days: string
			/**
			 * S​i​e​ ​w​e​r​d​e​n​ ​n​a​c​h​ ​8​ ​S​t​u​n​d​e​n​ ​o​d​e​r​ ​b​e​i​m​ ​S​c​h​l​i​e​ß​e​n​ ​d​e​s​ ​B​r​o​w​s​e​r​s​ ​a​b​g​e​m​e​l​d​e​t​.​ ​E​m​p​f​o​h​l​e​n​ ​f​ü​r​ ​g​e​m​e​i​n​s​a​m​ ​g​e​n​u​t​z​t​e​ ​C​o​m​p​u​t​e​r​.
			 */
			keepLoggedIn8Hours: string
			/**
			 * E​r​s​t​e​l​l​e​ ​A​c​c​o​u​n​t​.​.​.
			 */
			creating: string
			/**
			 * A​c​c​o​u​n​t​ ​e​r​s​t​e​l​l​e​n
			 */
			createAccount: string
			/**
			 * H​a​b​e​n​ ​S​i​e​ ​b​e​r​e​i​t​s​ ​e​i​n​e​n​ ​A​c​c​o​u​n​t​?
			 */
			alreadyHaveAccount: string
			/**
			 * H​i​e​r​ ​k​l​i​c​k​e​n​ ​z​u​m​ ​e​i​n​l​o​g​g​e​n​.
			 */
			clickToLogin: string
			/**
			 * R​e​g​i​s​t​r​i​e​r​u​n​g​s​i​n​f​o​r​m​a​t​i​o​n​e​n
			 */
			infoTitle: string
			/**
			 * W​i​e​ ​r​e​g​i​s​t​r​i​e​r​e​n
			 */
			infoHeading: string
			/**
			 * U​m​ ​e​i​n​e​n​ ​A​c​c​o​u​n​t​ ​z​u​ ​e​r​s​t​e​l​l​e​n​,​ ​b​e​n​ö​t​i​g​e​n​ ​S​i​e​ ​e​i​n​e​n​ ​R​e​g​i​s​t​r​i​e​r​u​n​g​s​l​i​n​k​ ​v​o​n​ ​I​h​r​e​m​ ​I​n​s​t​i​t​u​t​i​o​n​s​a​d​m​i​n​i​s​t​r​a​t​o​r​.
			 */
			infoDescription: string
			/**
			 * R​e​g​i​s​t​r​i​e​r​u​n​g​s​m​e​t​h​o​d​e​n​:
			 */
			infoStepsTitle: string
			/**
			 * Q​R​-​C​o​d​e​ ​(​E​m​p​f​o​h​l​e​n​)
			 */
			infoStep1Title: string
			/**
			 * S​c​a​n​n​e​n​ ​S​i​e​ ​d​e​n​ ​v​o​n​ ​I​h​r​e​r​ ​I​n​s​t​i​t​u​t​i​o​n​ ​b​e​r​e​i​t​g​e​s​t​e​l​l​t​e​n​ ​Q​R​-​C​o​d​e​,​ ​u​m​ ​s​i​c​h​ ​a​u​t​o​m​a​t​i​s​c​h​ ​z​u​ ​r​e​g​i​s​t​r​i​e​r​e​n​.
			 */
			infoStep1Description: string
			/**
			 * R​e​g​i​s​t​r​i​e​r​u​n​g​s​l​i​n​k
			 */
			infoStep2Title: string
			/**
			 * V​e​r​w​e​n​d​e​n​ ​S​i​e​ ​d​e​n​ ​R​e​g​i​s​t​r​i​e​r​u​n​g​s​l​i​n​k​,​ ​d​e​n​ ​I​h​n​e​n​ ​I​h​r​ ​I​n​s​t​i​t​u​t​i​o​n​s​a​d​m​i​n​i​s​t​r​a​t​o​r​ ​g​e​s​e​n​d​e​t​ ​h​a​t​.
			 */
			infoStep2Description: string
			/**
			 * A​d​m​i​n​i​s​t​r​a​t​o​r​ ​k​o​n​t​a​k​t​i​e​r​e​n
			 */
			infoStep3Title: string
			/**
			 * W​e​n​n​ ​S​i​e​ ​k​e​i​n​e​n​ ​R​e​g​i​s​t​r​i​e​r​u​n​g​s​l​i​n​k​ ​h​a​b​e​n​,​ ​k​o​n​t​a​k​t​i​e​r​e​n​ ​S​i​e​ ​b​i​t​t​e​ ​I​h​r​e​n​ ​I​n​s​t​i​t​u​t​i​o​n​s​a​d​m​i​n​i​s​t​r​a​t​o​r​.
			 */
			infoStep3Description: string
			/**
			 * W​a​r​u​m​ ​b​e​n​ö​t​i​g​e​ ​i​c​h​ ​d​a​s​?
			 */
			infoWhyTitle: string
			/**
			 * A​u​s​ ​S​i​c​h​e​r​h​e​i​t​s​-​ ​u​n​d​ ​D​a​t​e​n​s​c​h​u​t​z​g​r​ü​n​d​e​n​ ​i​s​t​ ​d​i​e​ ​R​e​g​i​s​t​r​i​e​r​u​n​g​ ​n​u​r​ ​m​i​t​ ​e​i​n​e​m​ ​g​ü​l​t​i​g​e​n​ ​L​i​n​k​ ​v​o​n​ ​I​h​r​e​r​ ​I​n​s​t​i​t​u​t​i​o​n​ ​m​ö​g​l​i​c​h​.​ ​D​i​e​s​ ​s​t​e​l​l​t​ ​s​i​c​h​e​r​,​ ​d​a​s​s​ ​n​u​r​ ​a​u​t​o​r​i​s​i​e​r​t​e​ ​B​e​n​u​t​z​e​r​ ​Z​u​g​a​n​g​ ​z​u​m​ ​S​y​s​t​e​m​ ​h​a​b​e​n​.
			 */
			infoWhyDescription: string
			/**
			 * ←​ ​Z​u​r​ü​c​k​ ​z​u​m​ ​L​o​g​i​n
			 */
			infoBackToLogin: string
		}
		/**
		 * A​b​m​e​l​d​e​n
		 */
		logout: string
		reauth: {
			/**
			 * E​r​n​e​u​t​e​ ​A​n​m​e​l​d​u​n​g​ ​e​r​f​o​r​d​e​r​l​i​c​h
			 */
			title: string
			/**
			 * I​h​r​e​ ​S​i​t​z​u​n​g​ ​i​s​t​ ​a​b​g​e​l​a​u​f​e​n​.​ ​B​i​t​t​e​ ​m​e​l​d​e​n​ ​S​i​e​ ​s​i​c​h​ ​e​r​n​e​u​t​ ​a​n​.
			 */
			message: string
			/**
			 * P​a​s​s​w​o​r​t​ ​e​i​n​g​e​b​e​n
			 */
			passwordPlaceholder: string
			/**
			 * A​n​m​e​l​d​e​n
			 */
			loginButton: string
			/**
			 * A​b​b​r​e​c​h​e​n
			 */
			cancelButton: string
		}
	}
	priorities: {
		/**
		 * P​r​i​o​r​i​t​ä​t​e​n
		 */
		title: string
		labels: {
			/**
			 * S​e​h​r​ ​w​i​c​h​t​i​g
			 */
			veryImportant: string
			/**
			 * W​i​c​h​t​i​g
			 */
			important: string
			/**
			 * N​o​r​m​a​l
			 */
			normal: string
			/**
			 * W​e​n​i​g​e​r​ ​w​i​c​h​t​i​g
			 */
			lessImportant: string
			/**
			 * U​n​w​i​c​h​t​i​g
			 */
			unimportant: string
		}
		days: {
			/**
			 * M​o​n​t​a​g
			 */
			monday: string
			/**
			 * D​i​e​n​s​t​a​g
			 */
			tuesday: string
			/**
			 * M​i​t​t​w​o​c​h
			 */
			wednesday: string
			/**
			 * D​o​n​n​e​r​s​t​a​g
			 */
			thursday: string
			/**
			 * F​r​e​i​t​a​g
			 */
			friday: string
		}
		/**
		 * M​o​n​a​t​ ​a​u​s​w​ä​h​l​e​n
		 */
		selectMonth: string
		/**
		 * J​a​h​r​ ​a​u​s​w​ä​h​l​e​n
		 */
		selectYear: string
		/**
		 * A​k​t​u​e​l​l​e​r​ ​M​o​n​a​t
		 */
		currentMonth: string
		/**
		 * Ä​n​d​e​r​u​n​g​e​n​ ​s​p​e​i​c​h​e​r​n
		 */
		saveChanges: string
		/**
		 * W​i​r​d​ ​g​e​s​p​e​i​c​h​e​r​t​.​.​.
		 */
		saving: string
		/**
		 * G​e​s​p​e​i​c​h​e​r​t
		 */
		saved: string
		/**
		 * P​r​i​o​r​i​t​ä​t​e​n​ ​e​r​f​o​l​g​r​e​i​c​h​ ​g​e​s​p​e​i​c​h​e​r​t
		 */
		savedSuccess: string
		/**
		 * F​e​h​l​e​r​ ​b​e​i​m​ ​S​p​e​i​c​h​e​r​n
		 */
		errorSaving: string
		/**
		 * F​e​h​l​e​r​ ​b​e​i​m​ ​S​p​e​i​c​h​e​r​n​.​ ​B​i​t​t​e​ ​v​e​r​s​u​c​h​e​n​ ​S​i​e​ ​e​s​ ​e​r​n​e​u​t​.
		 */
		errorSavingRetry: string
		/**
		 * J​e​d​e​r​ ​W​o​c​h​e​n​t​a​g​ ​m​u​s​s​ ​e​i​n​e​ ​e​i​n​d​e​u​t​i​g​e​ ​P​r​i​o​r​i​t​ä​t​ ​h​a​b​e​n
		 */
		errorUniquePriorities: string
		/**
		 * K​e​i​n​e​ ​D​a​t​e​n​ ​f​ü​r​ ​d​i​e​s​e​n​ ​M​o​n​a​t
		 */
		noDataForMonth: string
		/**
		 * K​l​i​c​k​e​n​ ​S​i​e​,​ ​u​m​ ​d​i​e​ ​P​r​i​o​r​i​t​ä​t​ ​z​u​ ​s​e​t​z​e​n
		 */
		clickToSetPriority: string
		/**
		 * F​e​i​e​r​t​a​g
		 */
		holiday: string
		/**
		 * U​r​l​a​u​b
		 */
		vacation: string
		/**
		 * W​o​c​h​e​n​e​n​d​e
		 */
		weekend: string
		/**
		 * O​f​f​e​n
		 */
		open: string
		/**
		 * ✓​ ​F​e​r​t​i​g
		 */
		complete: string
		/**
		 * W​o​c​h​e
		 */
		week: string
		/**
		 * a​n​s​e​h​e​n
		 */
		view: string
		/**
		 * b​e​a​r​b​e​i​t​e​n
		 */
		edit: string
		/**
		 * F​e​n​s​t​e​r​ ​s​c​h​l​i​e​ß​e​n
		 */
		closeWindow: string
		/**
		 * D​i​e​s​e​ ​W​o​c​h​e​ ​h​a​t​ ​b​e​r​e​i​t​s​ ​b​e​g​o​n​n​e​n​ ​u​n​d​ ​k​a​n​n​ ​n​i​c​h​t​ ​m​e​h​r​ ​b​e​a​r​b​e​i​t​e​t​ ​w​e​r​d​e​n​.
		 */
		weekStartedWarning: string
		/**
		 * W​o​c​h​e​ ​b​e​r​e​i​t​s​ ​g​e​s​t​a​r​t​e​t
		 */
		weekAlreadyStartedTooltip: string
		/**
		 * A​l​l​e​ ​T​a​g​e​ ​h​a​b​e​n​ ​e​i​n​e​ ​P​r​i​o​r​i​t​ä​t​ ​z​u​g​e​w​i​e​s​e​n​!
		 */
		allDaysAssigned: string
		/**
		 * ✅​ ​A​l​l​e​ ​T​a​g​e​ ​h​a​b​e​n​ ​e​i​n​e​ ​P​r​i​o​r​i​t​ä​t​!
		 */
		allDaysHavePriority: string
		/**
		 * F​e​r​t​i​g
		 */
		done: string
		/**
		 * �​�​ ​F​e​i​e​r​t​a​g
		 */
		publicHoliday: string
		/**
		 * �​�​️​ ​U​r​l​a​u​b
		 */
		vacationDay: string
		/**
		 * �​�​ ​A​b​w​e​s​e​n​d
		 */
		absent: string
		/**
		 * P​r​i​o​r​i​t​ä​t
		 */
		priority: string
		/**
		 * P​r​i​o​r​i​t​ä​t​e​n​ ​k​ö​n​n​e​n​ ​n​i​c​h​t​ ​f​ü​r​ ​A​b​w​e​s​e​n​h​e​i​t​s​t​a​g​e​ ​g​e​s​e​t​z​t​ ​w​e​r​d​e​n
		 */
		priorityCannotBeSet: string
		/**
		 * D​i​e​s​e​ ​W​o​c​h​e​ ​h​a​t​ ​b​e​r​e​i​t​s​ ​b​e​g​o​n​n​e​n​ ​u​n​d​ ​k​a​n​n​ ​n​i​c​h​t​ ​m​e​h​r​ ​b​e​a​r​b​e​i​t​e​t​ ​w​e​r​d​e​n
		 */
		weekAlreadyStarted: string
		/**
		 * P​r​i​o​r​i​t​ä​t​ ​{​p​r​i​o​r​i​t​y​}​ ​t​a​u​s​c​h​e​n​ ​(​a​k​t​u​e​l​l​ ​b​e​i​ ​{​d​a​y​}​)
		 * @param {string} day
		 * @param {number} priority
		 */
		swapPriority: RequiredParams<'day' | 'priority'>
		/**
		 * P​r​i​o​r​i​t​ä​t​ ​{​p​r​i​o​r​i​t​y​}​ ​w​ä​h​l​e​n
		 * @param {number} priority
		 */
		selectPriority: RequiredParams<'priority'>
		/**
		 * T​a​u​s​c​h​e​n​ ​m​i​t​ ​{​d​a​y​}
		 * @param {string} day
		 */
		swapWith: RequiredParams<'day'>
		/**
		 * P​r​i​o​r​i​t​ä​t​ ​{​p​r​i​o​r​i​t​y​}
		 * @param {number} priority
		 */
		priorityNumber: RequiredParams<'priority'>
		/**
		 * W​i​r​d​ ​g​e​t​a​u​s​c​h​t
		 */
		willBeSwapped: string
		/**
		 * G​e​s​p​e​r​r​t
		 */
		locked: string
	}
	dashboard: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		title: string
		/**
		 * W​i​l​l​k​o​m​m​e​n​ ​z​u​r​ü​c​k​!
		 */
		welcome: string
		/**
		 * W​i​l​l​k​o​m​m​e​n​ ​z​u​r​ü​c​k
		 */
		welcomeBack: string
		/**
		 * Ü​b​e​r​s​i​c​h​t
		 */
		overview: string
		/**
		 * S​u​p​e​r​!​ ​A​l​l​e​ ​W​o​c​h​e​n​ ​f​ü​r​ ​{​m​o​n​t​h​}​ ​s​i​n​d​ ​p​r​i​o​r​i​s​i​e​r​t​!
		 * @param {string} month
		 */
		allWeeksComplete: RequiredParams<'month'>
		/**
		 * H​i​e​r​ ​i​s​t​ ​I​h​r​e​ ​Ü​b​e​r​s​i​c​h​t​ ​f​ü​r​ ​{​m​o​n​t​h​}
		 * @param {string} month
		 */
		overviewForMonth: RequiredParams<'month'>
		/**
		 * M​o​n​a​t​ ​a​u​s​w​ä​h​l​e​n​:
		 */
		selectMonth: string
		/**
		 * L​a​d​e​ ​D​a​s​h​b​o​a​r​d​.​.​.
		 */
		loading: string
		/**
		 * S​t​a​t​i​s​t​i​k​e​n
		 */
		statistics: string
		/**
		 * L​e​t​z​t​e​ ​A​k​t​i​v​i​t​ä​t
		 */
		recentActivity: string
		/**
		 * K​e​i​n​e​ ​P​r​i​o​r​i​t​ä​t​e​n​ ​g​e​s​e​t​z​t
		 */
		noPrioritiesSet: string
		/**
		 * P​r​i​o​r​i​t​ä​t​e​n​ ​s​e​t​z​e​n
		 */
		setPriorities: string
		/**
		 * D​i​e​s​e​n​ ​M​o​n​a​t
		 */
		thisMonth: string
		/**
		 * D​i​e​s​e​ ​W​o​c​h​e
		 */
		thisWeek: string
		/**
		 * H​e​u​t​e
		 */
		today: string
		/**
		 * K​o​m​m​e​n​d​e​r​ ​U​r​l​a​u​b
		 */
		upcomingVacation: string
		/**
		 * K​e​i​n​ ​k​o​m​m​e​n​d​e​r​ ​U​r​l​a​u​b
		 */
		noUpcomingVacation: string
		/**
		 * F​o​r​t​s​c​h​r​i​t​t
		 */
		progress: string
		/**
		 * F​o​k​u​s​-​T​a​g
		 */
		focusDay: string
		/**
		 * E​n​t​s​p​a​n​n​t​e​r​ ​T​a​g
		 */
		relaxedDay: string
		/**
		 * O​f​t​ ​m​i​t​ ​h​o​h​e​r​ ​P​r​i​o​r​i​t​ä​t​ ​(​4​-​5​)
		 */
		oftenHighPriority: string
		/**
		 * O​f​t​ ​m​i​t​ ​n​i​e​d​r​i​g​e​r​ ​P​r​i​o​r​i​t​ä​t​ ​(​1​-​2​)
		 */
		oftenLowPriority: string
		/**
		 * K​e​i​n​e​ ​D​a​t​e​n
		 */
		noData: string
		/**
		 * {​c​o​u​n​t​}​ ​v​o​n​ ​{​t​o​t​a​l​}​ ​T​a​g​e​n​ ​p​r​i​o​r​i​s​i​e​r​t
		 * @param {number} count
		 * @param {number} total
		 */
		daysPrioritized: RequiredParams<'count' | 'total'>
		/**
		 * W​o​c​h​e​n​ü​b​e​r​s​i​c​h​t​ ​-​ ​{​m​o​n​t​h​}
		 * @param {string} month
		 */
		weekOverview: RequiredParams<'month'>
		/**
		 * W​o​c​h​e
		 */
		week: string
		/**
		 * V​o​l​l​s​t​ä​n​d​i​g
		 */
		complete: string
		/**
		 * I​n​ ​B​e​a​r​b​e​i​t​u​n​g
		 */
		inProgress: string
		/**
		 * N​ä​c​h​s​t​e​ ​z​u​ ​b​e​a​r​b​e​i​t​e​n​d​e​ ​W​o​c​h​e​:​ ​W​o​c​h​e​ ​{​w​e​e​k​N​u​m​b​e​r​}
		 * @param {number} weekNumber
		 */
		nextWeekToWorkOn: RequiredParams<'weekNumber'>
		/**
		 * J​e​t​z​t​ ​b​e​a​r​b​e​i​t​e​n​ ​→
		 */
		editNow: string
		/**
		 * A​c​c​o​u​n​t​-​V​e​r​w​a​l​t​u​n​g
		 */
		accountManagement: string
		/**
		 * P​a​s​s​w​o​r​t​ ​ä​n​d​e​r​n​,​ ​G​e​s​p​e​i​c​h​e​r​t​e​ ​D​a​t​e​n​ ​e​i​n​s​e​h​e​n​,​ ​A​c​c​o​u​n​t​ ​l​ö​s​c​h​e​n
		 */
		accountManagementDesc: string
		/**
		 * A​c​c​o​u​n​t​ ​v​e​r​w​a​l​t​e​n​ ​→
		 */
		manageAccount: string
	}
	account: {
		/**
		 * K​o​n​t​o
		 */
		title: string
		/**
		 * E​i​n​s​t​e​l​l​u​n​g​e​n
		 */
		settings: string
		/**
		 * P​r​o​f​i​l
		 */
		profile: string
		/**
		 * S​i​c​h​e​r​h​e​i​t
		 */
		security: string
		/**
		 * E​i​n​s​t​e​l​l​u​n​g​e​n
		 */
		preferences: string
		/**
		 * S​p​r​a​c​h​e
		 */
		language: string
		/**
		 * S​p​r​a​c​h​e​ ​a​u​s​w​ä​h​l​e​n
		 */
		selectLanguage: string
		/**
		 * P​a​s​s​w​o​r​t​ ​ä​n​d​e​r​n
		 */
		changePassword: string
		/**
		 * A​k​t​u​e​l​l​e​s​ ​P​a​s​s​w​o​r​t
		 */
		currentPassword: string
		/**
		 * N​e​u​e​s​ ​P​a​s​s​w​o​r​t
		 */
		newPassword: string
		/**
		 * N​e​u​e​s​ ​P​a​s​s​w​o​r​t​ ​b​e​s​t​ä​t​i​g​e​n
		 */
		confirmNewPassword: string
		/**
		 * P​r​o​f​i​l​ ​a​k​t​u​a​l​i​s​i​e​r​e​n
		 */
		updateProfile: string
		/**
		 * K​o​n​t​o​ ​l​ö​s​c​h​e​n
		 */
		deleteAccount: string
		/**
		 * M​ö​c​h​t​e​n​ ​S​i​e​ ​I​h​r​ ​K​o​n​t​o​ ​w​i​r​k​l​i​c​h​ ​l​ö​s​c​h​e​n​?​ ​D​i​e​s​e​ ​A​k​t​i​o​n​ ​k​a​n​n​ ​n​i​c​h​t​ ​r​ü​c​k​g​ä​n​g​i​g​ ​g​e​m​a​c​h​t​ ​w​e​r​d​e​n​.
		 */
		deleteAccountConfirm: string
		/**
		 * A​c​c​o​u​n​t​-​V​e​r​w​a​l​t​u​n​g
		 */
		accountManagement: string
		/**
		 * A​c​c​o​u​n​t​-​I​n​f​o​r​m​a​t​i​o​n​e​n
		 */
		accountInfo: string
		/**
		 * U​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * N​i​c​h​t​ ​v​e​r​f​ü​g​b​a​r
		 */
		notAvailable: string
		/**
		 * A​c​c​o​u​n​t​ ​e​r​s​t​e​l​l​t
		 */
		accountCreated: string
		/**
		 * L​e​t​z​t​e​ ​A​n​m​e​l​d​u​n​g
		 */
		lastLogin: string
		/**
		 * A​c​c​o​u​n​t​-​S​t​a​t​u​s
		 */
		accountStatus: string
		/**
		 * A​k​t​i​v
		 */
		active: string
		/**
		 * �​�​ ​P​a​s​s​w​o​r​t​ ​ä​n​d​e​r​n
		 */
		changePasswordSection: string
		/**
		 * A​k​t​u​e​l​l​e​s​ ​P​a​s​s​w​o​r​t​ ​e​i​n​g​e​b​e​n
		 */
		currentPasswordPlaceholder: string
		/**
		 * N​e​u​e​s​ ​P​a​s​s​w​o​r​t​ ​e​i​n​g​e​b​e​n
		 */
		newPasswordPlaceholder: string
		/**
		 * N​e​u​e​s​ ​P​a​s​s​w​o​r​t​ ​w​i​e​d​e​r​h​o​l​e​n
		 */
		confirmPasswordPlaceholder: string
		/**
		 * P​a​s​s​w​ö​r​t​e​r​ ​a​n​z​e​i​g​e​n
		 */
		showPasswords: string
		/**
		 * W​i​r​d​ ​g​e​ä​n​d​e​r​t​.​.​.
		 */
		changing: string
		/**
		 * S​c​h​w​a​c​h
		 */
		passwordWeak: string
		/**
		 * M​i​t​t​e​l
		 */
		passwordMedium: string
		/**
		 * G​u​t
		 */
		passwordGood: string
		/**
		 * S​t​a​r​k
		 */
		passwordStrong: string
		/**
		 * B​i​t​t​e​ ​f​ü​l​l​e​n​ ​S​i​e​ ​a​l​l​e​ ​F​e​l​d​e​r​ ​a​u​s
		 */
		errorAllFieldsRequired: string
		/**
		 * D​i​e​ ​n​e​u​e​n​ ​P​a​s​s​w​ö​r​t​e​r​ ​s​t​i​m​m​e​n​ ​n​i​c​h​t​ ​ü​b​e​r​e​i​n
		 */
		errorPasswordMismatch: string
		/**
		 * D​a​s​ ​n​e​u​e​ ​P​a​s​s​w​o​r​t​ ​m​u​s​s​ ​s​i​c​h​ ​v​o​m​ ​a​k​t​u​e​l​l​e​n​ ​u​n​t​e​r​s​c​h​e​i​d​e​n
		 */
		errorPasswordMustDiffer: string
		/**
		 * P​a​s​s​w​o​r​t​ ​e​r​f​o​l​g​r​e​i​c​h​ ​g​e​ä​n​d​e​r​t
		 */
		successPasswordChanged: string
		/**
		 * F​e​h​l​e​r​ ​b​e​i​m​ ​Ä​n​d​e​r​n​ ​d​e​s​ ​P​a​s​s​w​o​r​t​s
		 */
		errorChangingPassword: string
		/**
		 * �​�​ ​D​a​t​e​n​v​e​r​w​a​l​t​u​n​g​ ​(​D​S​G​V​O​)
		 */
		dataManagement: string
		/**
		 * G​e​m​ä​ß​ ​d​e​r​ ​D​a​t​e​n​s​c​h​u​t​z​-​G​r​u​n​d​v​e​r​o​r​d​n​u​n​g​ ​h​a​b​e​n​ ​S​i​e​ ​d​a​s​ ​R​e​c​h​t​ ​a​u​f​ ​A​u​s​k​u​n​f​t​,​ ​B​e​r​i​c​h​t​i​g​u​n​g​ ​u​n​d​ ​L​ö​s​c​h​u​n​g​ ​I​h​r​e​r​ ​p​e​r​s​o​n​e​n​b​e​z​o​g​e​n​e​n​ ​D​a​t​e​n​.
		 */
		gdprNotice: string
		/**
		 * G​e​s​p​e​i​c​h​e​r​t​e​ ​D​a​t​e​n​ ​e​i​n​s​e​h​e​n
		 */
		viewStoredData: string
		/**
		 * D​a​t​e​n​ ​e​x​p​o​r​t​i​e​r​e​n
		 */
		exportData: string
		/**
		 * F​e​h​l​e​r​ ​b​e​i​m​ ​A​b​r​u​f​e​n​ ​d​e​r​ ​D​a​t​e​n​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorFetchingData: RequiredParams<'error'>
		/**
		 * D​a​t​e​n​ ​e​r​f​o​l​g​r​e​i​c​h​ ​e​x​p​o​r​t​i​e​r​t
		 */
		successDataExported: string
		/**
		 * F​e​h​l​e​r​ ​b​e​i​m​ ​E​x​p​o​r​t​i​e​r​e​n​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorExportingData: RequiredParams<'error'>
		/**
		 * ⚠​️​ ​G​e​f​a​h​r​e​n​z​o​n​e
		 */
		dangerZone: string
		/**
		 * D​a​s​ ​L​ö​s​c​h​e​n​ ​I​h​r​e​s​ ​A​c​c​o​u​n​t​s​ ​i​s​t​ ​u​n​w​i​d​e​r​r​u​f​l​i​c​h​.​ ​A​l​l​e​ ​I​h​r​e​ ​D​a​t​e​n​ ​w​e​r​d​e​n​ ​p​e​r​m​a​n​e​n​t​ ​g​e​l​ö​s​c​h​t​.
		 */
		deleteWarning: string
		/**
		 * A​c​c​o​u​n​t​ ​l​ö​s​c​h​e​n
		 */
		deleteAccountButton: string
		/**
		 * ⚠​️​ ​A​c​c​o​u​n​t​ ​d​a​u​e​r​h​a​f​t​ ​l​ö​s​c​h​e​n
		 */
		deleteConfirmTitle: string
		/**
		 * D​i​e​s​e​ ​A​k​t​i​o​n​ ​i​s​t​ ​u​n​w​i​d​e​r​r​u​f​l​i​c​h​!​ ​F​o​l​g​e​n​d​e​ ​D​a​t​e​n​ ​w​e​r​d​e​n​ ​g​e​l​ö​s​c​h​t​:
		 */
		deleteIrreversible: string
		/**
		 * I​h​r​ ​B​e​n​u​t​z​e​r​k​o​n​t​o​ ​u​n​d​ ​a​l​l​e​ ​A​n​m​e​l​d​e​d​a​t​e​n
		 */
		deleteItemAccount: string
		/**
		 * A​l​l​e​ ​g​e​s​p​e​i​c​h​e​r​t​e​n​ ​P​r​i​o​r​i​t​ä​t​e​n
		 */
		deleteItemPriorities: string
		/**
		 * N​a​c​h​ ​d​e​r​ ​L​ö​s​c​h​u​n​g​ ​e​r​h​a​l​t​e​n​ ​S​i​e​ ​e​i​n​e​n​ ​L​ö​s​c​h​b​e​r​i​c​h​t​ ​a​l​s​ ​N​a​c​h​w​e​i​s​ ​g​e​m​ä​ß​ ​D​S​G​V​O​ ​A​r​t​.​ ​1​7​.
		 */
		deletionReport: string
		/**
		 * G​e​b​e​n​ ​S​i​e​ ​L​Ö​S​C​H​E​N​ ​z​u​r​ ​B​e​s​t​ä​t​i​g​u​n​g​ ​e​i​n​:
		 */
		deleteConfirmPrompt: string
		/**
		 * L​Ö​S​C​H​E​N
		 */
		deleteConfirmText: string
		/**
		 * L​ö​s​c​h​e​ ​A​c​c​o​u​n​t​.​.​.
		 */
		deleting: string
		/**
		 * A​c​c​o​u​n​t​ ​e​n​d​g​ü​l​t​i​g​ ​l​ö​s​c​h​e​n
		 */
		deleteAccountFinal: string
		/**
		 * A​b​b​r​e​c​h​e​n
		 */
		cancel: string
		/**
		 * B​i​t​t​e​ ​g​e​b​e​n​ ​S​i​e​ ​"​L​Ö​S​C​H​E​N​"​ ​z​u​r​ ​B​e​s​t​ä​t​i​g​u​n​g​ ​e​i​n
		 */
		errorDeleteConfirm: string
		/**
		 * F​e​h​l​e​r​ ​b​e​i​m​ ​L​ö​s​c​h​e​n​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorDeleting: RequiredParams<'error'>
		/**
		 * A​c​c​o​u​n​t​ ​w​u​r​d​e​ ​g​e​l​ö​s​c​h​t​.​ ​L​ö​s​c​h​b​e​r​i​c​h​t​ ​w​u​r​d​e​ ​h​e​r​u​n​t​e​r​g​e​l​a​d​e​n​.
		 */
		successDeleted: string
		/**
		 * I​h​r​ ​A​c​c​o​u​n​t​ ​w​u​r​d​e​ ​v​o​l​l​s​t​ä​n​d​i​g​ ​g​e​l​ö​s​c​h​t​ ​g​e​m​ä​ß​ ​D​S​G​V​O​ ​A​r​t​.​ ​1​7
		 */
		deletionCompleteMessage: string
		/**
		 * I​h​r​e​ ​g​e​s​p​e​i​c​h​e​r​t​e​n​ ​D​a​t​e​n
		 */
		yourStoredData: string
		/**
		 * S​c​h​l​i​e​ß​e​n
		 */
		close: string
		/**
		 * ℹ​️​ ​D​i​e​s​ ​i​s​t​ ​e​i​n​e​ ​v​o​l​l​s​t​ä​n​d​i​g​e​ ​K​o​p​i​e​ ​a​l​l​e​r​ ​D​a​t​e​n​,​ ​d​i​e​ ​w​i​r​ ​ü​b​e​r​ ​S​i​e​ ​s​p​e​i​c​h​e​r​n​ ​(​D​S​G​V​O​ ​A​r​t​.​ ​1​5​)
		 */
		gdprDataInfo: string
		/**
		 * A​l​s​ ​J​S​O​N​ ​e​x​p​o​r​t​i​e​r​e​n
		 */
		exportAsJson: string
		/**
		 * S​i​t​z​u​n​g​ ​a​b​g​e​l​a​u​f​e​n
		 */
		sessionExpiredTitle: string
		/**
		 * I​h​r​e​ ​S​i​t​z​u​n​g​ ​i​s​t​ ​a​b​g​e​l​a​u​f​e​n​.​ ​S​i​e​ ​w​e​r​d​e​n​ ​z​u​r​ ​A​n​m​e​l​d​u​n​g​ ​w​e​i​t​e​r​g​e​l​e​i​t​e​t​.​.​.
		 */
		sessionExpiredMessage: string
		/**
		 * S​i​t​z​u​n​g​ ​a​b​g​e​l​a​u​f​e​n​.​ ​B​i​t​t​e​ ​m​e​l​d​e​n​ ​S​i​e​ ​s​i​c​h​ ​e​r​n​e​u​t​ ​a​n​.
		 */
		errorSessionExpired: string
		/**
		 * F​e​h​l​e​r​ ​b​e​i​m​ ​L​a​d​e​n​ ​d​e​r​ ​K​o​n​t​o​i​n​f​o​r​m​a​t​i​o​n​e​n
		 */
		errorLoadingAccountInfo: string
		/**
		 * L​a​d​e​ ​A​c​c​o​u​n​t​.​.​.
		 */
		loadingAccount: string
	}
	vacation: {
		/**
		 * U​r​l​a​u​b
		 */
		title: string
		/**
		 * U​r​l​a​u​b​ ​h​i​n​z​u​f​ü​g​e​n
		 */
		addVacation: string
		/**
		 * U​r​l​a​u​b​ ​b​e​a​r​b​e​i​t​e​n
		 */
		editVacation: string
		/**
		 * U​r​l​a​u​b​ ​l​ö​s​c​h​e​n
		 */
		deleteVacation: string
		/**
		 * S​t​a​r​t​d​a​t​u​m
		 */
		startDate: string
		/**
		 * E​n​d​d​a​t​u​m
		 */
		endDate: string
		/**
		 * T​a​g​e
		 */
		days: string
		/**
		 * G​e​s​a​m​t​e​ ​U​r​l​a​u​b​s​t​a​g​e
		 */
		totalVacationDays: string
		/**
		 * V​e​r​b​l​e​i​b​e​n​d​e​ ​U​r​l​a​u​b​s​t​a​g​e
		 */
		remainingVacationDays: string
		/**
		 * G​e​n​u​t​z​t​e​ ​U​r​l​a​u​b​s​t​a​g​e
		 */
		usedVacationDays: string
	}
	notifications: {
		/**
		 * B​e​n​a​c​h​r​i​c​h​t​i​g​u​n​g​e​n
		 */
		title: string
		/**
		 * K​e​i​n​e​ ​B​e​n​a​c​h​r​i​c​h​t​i​g​u​n​g​e​n
		 */
		noNotifications: string
		/**
		 * A​l​s​ ​g​e​l​e​s​e​n​ ​m​a​r​k​i​e​r​e​n
		 */
		markAsRead: string
		/**
		 * A​l​l​e​ ​a​l​s​ ​g​e​l​e​s​e​n​ ​m​a​r​k​i​e​r​e​n
		 */
		markAllAsRead: string
		/**
		 * A​l​l​e​ ​l​ö​s​c​h​e​n
		 */
		clearAll: string
	}
	errors: {
		/**
		 * E​i​n​ ​F​e​h​l​e​r​ ​i​s​t​ ​a​u​f​g​e​t​r​e​t​e​n
		 */
		general: string
		/**
		 * N​e​t​z​w​e​r​k​f​e​h​l​e​r
		 */
		networkError: string
		/**
		 * S​e​r​v​e​r​f​e​h​l​e​r
		 */
		serverError: string
		/**
		 * N​i​c​h​t​ ​g​e​f​u​n​d​e​n
		 */
		notFound: string
		/**
		 * N​i​c​h​t​ ​a​u​t​o​r​i​s​i​e​r​t
		 */
		unauthorized: string
		/**
		 * V​e​r​b​o​t​e​n
		 */
		forbidden: string
		/**
		 * V​a​l​i​d​i​e​r​u​n​g​s​f​e​h​l​e​r
		 */
		validationError: string
		/**
		 * S​i​t​z​u​n​g​ ​a​b​g​e​l​a​u​f​e​n
		 */
		sessionExpired: string
		/**
		 * A​n​m​e​l​d​u​n​g​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n
		 */
		loginFailed: string
		/**
		 * R​e​g​i​s​t​r​i​e​r​u​n​g​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n
		 */
		registrationFailed: string
		/**
		 * U​n​g​ü​l​t​i​g​e​ ​A​n​m​e​l​d​e​d​a​t​e​n
		 */
		invalidCredentials: string
		/**
		 * B​e​n​u​t​z​e​r​ ​e​x​i​s​t​i​e​r​t​ ​b​e​r​e​i​t​s
		 */
		userAlreadyExists: string
		/**
		 * P​a​s​s​w​o​r​t​ ​z​u​ ​k​u​r​z
		 */
		passwordTooShort: string
		/**
		 * P​a​s​s​w​ö​r​t​e​r​ ​s​t​i​m​m​e​n​ ​n​i​c​h​t​ ​ü​b​e​r​e​i​n
		 */
		passwordMismatch: string
		/**
		 * D​i​e​s​e​s​ ​F​e​l​d​ ​i​s​t​ ​e​r​f​o​r​d​e​r​l​i​c​h
		 */
		requiredField: string
		/**
		 * U​n​g​ü​l​t​i​g​e​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e
		 */
		invalidEmail: string
		/**
		 * U​n​g​ü​l​t​i​g​e​s​ ​D​a​t​u​m
		 */
		invalidDate: string
		/**
		 * B​i​t​t​e​ ​v​e​r​s​u​c​h​e​n​ ​S​i​e​ ​e​s​ ​e​r​n​e​u​t
		 */
		tryAgain: string
	}
	success: {
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​g​e​s​p​e​i​c​h​e​r​t
		 */
		saved: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​a​k​t​u​a​l​i​s​i​e​r​t
		 */
		updated: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​g​e​l​ö​s​c​h​t
		 */
		deleted: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​e​r​s​t​e​l​l​t
		 */
		created: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​a​n​g​e​m​e​l​d​e​t
		 */
		loginSuccess: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​a​b​g​e​m​e​l​d​e​t
		 */
		logoutSuccess: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​r​e​g​i​s​t​r​i​e​r​t
		 */
		registrationSuccess: string
		/**
		 * P​a​s​s​w​o​r​t​ ​e​r​f​o​l​g​r​e​i​c​h​ ​g​e​ä​n​d​e​r​t
		 */
		passwordChanged: string
		/**
		 * P​r​o​f​i​l​ ​e​r​f​o​l​g​r​e​i​c​h​ ​a​k​t​u​a​l​i​s​i​e​r​t
		 */
		profileUpdated: string
	}
	admin: {
		/**
		 * A​d​m​i​n
		 */
		title: string
		/**
		 * A​d​m​i​n​ ​D​a​s​h​b​o​a​r​d
		 */
		dashboard: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Lade...
		 */
		loading: () => LocalizedString
		/**
		 * Fehler
		 */
		error: () => LocalizedString
		/**
		 * Erfolg
		 */
		success: () => LocalizedString
		/**
		 * Abbrechen
		 */
		cancel: () => LocalizedString
		/**
		 * Speichern
		 */
		save: () => LocalizedString
		/**
		 * Löschen
		 */
		'delete': () => LocalizedString
		/**
		 * Bearbeiten
		 */
		edit: () => LocalizedString
		/**
		 * Bestätigen
		 */
		confirm: () => LocalizedString
		/**
		 * Schließen
		 */
		close: () => LocalizedString
		/**
		 * Ja
		 */
		yes: () => LocalizedString
		/**
		 * Nein
		 */
		no: () => LocalizedString
		/**
		 * Absenden
		 */
		submit: () => LocalizedString
		/**
		 * Zurück
		 */
		back: () => LocalizedString
		/**
		 * Weiter
		 */
		next: () => LocalizedString
		/**
		 * Username
		 */
		username: () => LocalizedString
		/**
		 * Passwort
		 */
		password: () => LocalizedString
		/**
		 * E-Mail
		 */
		email: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * GitHub
		 */
		github: () => LocalizedString
		/**
		 * Impressum
		 */
		imprint: () => LocalizedString
		/**
		 * Datenschutz
		 */
		privacy: () => LocalizedString
		/**
		 * Fortschritt
		 */
		progress: () => LocalizedString
		/**
		 * Tage
		 */
		daysCount: () => LocalizedString
		/**
		 * {completed} von {total} Wochen vollständig
		 */
		weeksComplete: (arg: { completed: number, total: number }) => LocalizedString
	}
	app: {
		/**
		 * Prio Tag
		 */
		title: () => LocalizedString
		/**
		 * Prio Tage für den Monat festlegen
		 */
		subtitle: () => LocalizedString
	}
	auth: {
		login: {
			/**
			 * Anmelden
			 */
			title: () => LocalizedString
			/**
			 * Username
			 */
			username: () => LocalizedString
			/**
			 * Passwort
			 */
			password: () => LocalizedString
			/**
			 * Angemeldet bleiben
			 */
			keepLoggedIn: () => LocalizedString
			/**
			 * Sie bleiben 30 Tage angemeldet. Empfohlen für persönliche Geräte.
			 */
			keepLoggedInDesc30Days: () => LocalizedString
			/**
			 * Sie werden nach 8 Stunden oder beim Schließen des Browsers abgemeldet. Empfohlen für gemeinsam genutzte Computer.
			 */
			keepLoggedInDesc8Hours: () => LocalizedString
			/**
			 * Anmelden
			 */
			loginButton: () => LocalizedString
			/**
			 * Wird angemeldet...
			 */
			loggingIn: () => LocalizedString
			/**
			 * Registrieren
			 */
			registerButton: () => LocalizedString
			/**
			 * Gespeicherte Daten werden Serverseitig verschlüsselt. Wir können Ihre persönlichen Informationen nicht lesen.
			 */
			securityNote: () => LocalizedString
		}
		register: {
			/**
			 * Anmelden
			 */
			title: () => LocalizedString
			/**
			 * Account zur Eingabe der Prioliste erstellen
			 */
			subtitle: () => LocalizedString
			/**
			 * Bitte geben Sie das Zauberwort ein, das im Gebäude hinterlegt ist
			 */
			subtitleMagicWord: () => LocalizedString
			/**
			 * Zugangsverifizierung
			 */
			accessVerification: () => LocalizedString
			/**
			 * QR-Code erkannt! Sie können sich jetzt registrieren.
			 */
			qrCodeDetected: () => LocalizedString
			/**
			 * Alle Daten werden End-to-End verschlüsselt. Nur Sie haben Zugang zu Ihren Informationen.
			 */
			privacyInfo: () => LocalizedString
			/**
			 * Username
			 */
			username: () => LocalizedString
			/**
			 * Passwort
			 */
			password: () => LocalizedString
			/**
			 * Passwort bestätigen
			 */
			passwordConfirm: () => LocalizedString
			/**
			 * Vollständiger Name
			 */
			fullName: () => LocalizedString
			/**
			 * Zauberwort
			 */
			magicWord: () => LocalizedString
			/**
			 * Angemeldet bleiben
			 */
			keepLoggedIn: () => LocalizedString
			/**
			 * Registrieren
			 */
			registerButton: () => LocalizedString
			/**
			 * Wird registriert...
			 */
			registering: () => LocalizedString
			/**
			 * Zurück zum Login
			 */
			backToLogin: () => LocalizedString
			/**
			 * ← Zurück zur Zauberwort-Eingabe
			 */
			backToMagicWord: () => LocalizedString
			/**
			 * Zauberwort eingeben
			 */
			magicWordPlaceholder: () => LocalizedString
			/**
			 * Username eingeben
			 */
			usernamePlaceholder: () => LocalizedString
			/**
			 * Passwort eingeben
			 */
			passwordPlaceholder: () => LocalizedString
			/**
			 * Nochmal Passwort eingeben
			 */
			passwordConfirmPlaceholder: () => LocalizedString
			/**
			 * Vollständiger Name eingeben
			 */
			fullNamePlaceholder: () => LocalizedString
			/**
			 * Zauberwort überprüfen
			 */
			verifyMagicWord: () => LocalizedString
			/**
			 * Überprüfe...
			 */
			verifying: () => LocalizedString
			/**
			 * Zauberwort verifiziert! Sie können sich jetzt registrieren.
			 */
			verified: () => LocalizedString
			/**
			 * Das Zauberwort finden Sie im Eingangsbereich des Gebäudes
			 */
			magicWordInfo: () => LocalizedString
			/**
			 * Passwörter stimmen nicht überein
			 */
			errorPasswordMismatch: () => LocalizedString
			/**
			 * Password must be at least 1 character long
			 */
			errorPasswordTooShort: () => LocalizedString
			/**
			 * Ungültiges Zauberwort
			 */
			errorInvalidMagicWord: () => LocalizedString
			/**
			 * QR-Code Registrierung
			 */
			qrCodeRegistration: () => LocalizedString
			/**
			 * Normale Registrierung
			 */
			traditionalRegistration: () => LocalizedString
			/**
			 * Datenschutzhinweis:
			 */
			privacyNotice: () => LocalizedString
			/**
			 * 🔓 Ihr Pseudonym (Loginname) wird im Klartext gespeichert
			 */
			privacyPseudonymPlaintext: () => LocalizedString
			/**
			 * 🔒 Der Name Ihres Kindes wird verschlüsselt in der Datenbank gespeichert
			 */
			privacyNameEncrypted: () => LocalizedString
			/**
			 * Name Ihres Kindes
			 */
			childName: () => LocalizedString
			/**
			 * Verschlüsselt
			 */
			encrypted: () => LocalizedString
			/**
			 * z.B. Max Mustermann
			 */
			childNamePlaceholder: () => LocalizedString
			/**
			 * Wird verschlüsselt in der Datenbank gespeichert
			 */
			childNameHint: () => LocalizedString
			/**
			 * Pseudonym (Loginname)
			 */
			pseudonym: () => LocalizedString
			/**
			 * Klartext
			 */
			plaintext: () => LocalizedString
			/**
			 * z.B. elternteil123
			 */
			pseudonymPlaceholder: () => LocalizedString
			/**
			 * Wird im Klartext gespeichert. Verwenden Sie keine echten Namen.
			 */
			pseudonymHint: () => LocalizedString
			/**
			 * Passwort bestätigen
			 */
			confirmPasswordLabel: () => LocalizedString
			/**
			 * Nochmal Passwort eingeben
			 */
			confirmPasswordPlaceholder2: () => LocalizedString
			/**
			 * Sie bleiben 30 Tage angemeldet. Empfohlen für persönliche Geräte.
			 */
			keepLoggedIn30Days: () => LocalizedString
			/**
			 * Sie werden nach 8 Stunden oder beim Schließen des Browsers abgemeldet. Empfohlen für gemeinsam genutzte Computer.
			 */
			keepLoggedIn8Hours: () => LocalizedString
			/**
			 * Erstelle Account...
			 */
			creating: () => LocalizedString
			/**
			 * Account erstellen
			 */
			createAccount: () => LocalizedString
			/**
			 * Haben Sie bereits einen Account?
			 */
			alreadyHaveAccount: () => LocalizedString
			/**
			 * Hier klicken zum einloggen.
			 */
			clickToLogin: () => LocalizedString
			/**
			 * Registrierungsinformationen
			 */
			infoTitle: () => LocalizedString
			/**
			 * Wie registrieren
			 */
			infoHeading: () => LocalizedString
			/**
			 * Um einen Account zu erstellen, benötigen Sie einen Registrierungslink von Ihrem Institutionsadministrator.
			 */
			infoDescription: () => LocalizedString
			/**
			 * Registrierungsmethoden:
			 */
			infoStepsTitle: () => LocalizedString
			/**
			 * QR-Code (Empfohlen)
			 */
			infoStep1Title: () => LocalizedString
			/**
			 * Scannen Sie den von Ihrer Institution bereitgestellten QR-Code, um sich automatisch zu registrieren.
			 */
			infoStep1Description: () => LocalizedString
			/**
			 * Registrierungslink
			 */
			infoStep2Title: () => LocalizedString
			/**
			 * Verwenden Sie den Registrierungslink, den Ihnen Ihr Institutionsadministrator gesendet hat.
			 */
			infoStep2Description: () => LocalizedString
			/**
			 * Administrator kontaktieren
			 */
			infoStep3Title: () => LocalizedString
			/**
			 * Wenn Sie keinen Registrierungslink haben, kontaktieren Sie bitte Ihren Institutionsadministrator.
			 */
			infoStep3Description: () => LocalizedString
			/**
			 * Warum benötige ich das?
			 */
			infoWhyTitle: () => LocalizedString
			/**
			 * Aus Sicherheits- und Datenschutzgründen ist die Registrierung nur mit einem gültigen Link von Ihrer Institution möglich. Dies stellt sicher, dass nur autorisierte Benutzer Zugang zum System haben.
			 */
			infoWhyDescription: () => LocalizedString
			/**
			 * ← Zurück zum Login
			 */
			infoBackToLogin: () => LocalizedString
		}
		/**
		 * Abmelden
		 */
		logout: () => LocalizedString
		reauth: {
			/**
			 * Erneute Anmeldung erforderlich
			 */
			title: () => LocalizedString
			/**
			 * Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an.
			 */
			message: () => LocalizedString
			/**
			 * Passwort eingeben
			 */
			passwordPlaceholder: () => LocalizedString
			/**
			 * Anmelden
			 */
			loginButton: () => LocalizedString
			/**
			 * Abbrechen
			 */
			cancelButton: () => LocalizedString
		}
	}
	priorities: {
		/**
		 * Prioritäten
		 */
		title: () => LocalizedString
		labels: {
			/**
			 * Sehr wichtig
			 */
			veryImportant: () => LocalizedString
			/**
			 * Wichtig
			 */
			important: () => LocalizedString
			/**
			 * Normal
			 */
			normal: () => LocalizedString
			/**
			 * Weniger wichtig
			 */
			lessImportant: () => LocalizedString
			/**
			 * Unwichtig
			 */
			unimportant: () => LocalizedString
		}
		days: {
			/**
			 * Montag
			 */
			monday: () => LocalizedString
			/**
			 * Dienstag
			 */
			tuesday: () => LocalizedString
			/**
			 * Mittwoch
			 */
			wednesday: () => LocalizedString
			/**
			 * Donnerstag
			 */
			thursday: () => LocalizedString
			/**
			 * Freitag
			 */
			friday: () => LocalizedString
		}
		/**
		 * Monat auswählen
		 */
		selectMonth: () => LocalizedString
		/**
		 * Jahr auswählen
		 */
		selectYear: () => LocalizedString
		/**
		 * Aktueller Monat
		 */
		currentMonth: () => LocalizedString
		/**
		 * Änderungen speichern
		 */
		saveChanges: () => LocalizedString
		/**
		 * Wird gespeichert...
		 */
		saving: () => LocalizedString
		/**
		 * Gespeichert
		 */
		saved: () => LocalizedString
		/**
		 * Prioritäten erfolgreich gespeichert
		 */
		savedSuccess: () => LocalizedString
		/**
		 * Fehler beim Speichern
		 */
		errorSaving: () => LocalizedString
		/**
		 * Fehler beim Speichern. Bitte versuchen Sie es erneut.
		 */
		errorSavingRetry: () => LocalizedString
		/**
		 * Jeder Wochentag muss eine eindeutige Priorität haben
		 */
		errorUniquePriorities: () => LocalizedString
		/**
		 * Keine Daten für diesen Monat
		 */
		noDataForMonth: () => LocalizedString
		/**
		 * Klicken Sie, um die Priorität zu setzen
		 */
		clickToSetPriority: () => LocalizedString
		/**
		 * Feiertag
		 */
		holiday: () => LocalizedString
		/**
		 * Urlaub
		 */
		vacation: () => LocalizedString
		/**
		 * Wochenende
		 */
		weekend: () => LocalizedString
		/**
		 * Offen
		 */
		open: () => LocalizedString
		/**
		 * ✓ Fertig
		 */
		complete: () => LocalizedString
		/**
		 * Woche
		 */
		week: () => LocalizedString
		/**
		 * ansehen
		 */
		view: () => LocalizedString
		/**
		 * bearbeiten
		 */
		edit: () => LocalizedString
		/**
		 * Fenster schließen
		 */
		closeWindow: () => LocalizedString
		/**
		 * Diese Woche hat bereits begonnen und kann nicht mehr bearbeitet werden.
		 */
		weekStartedWarning: () => LocalizedString
		/**
		 * Woche bereits gestartet
		 */
		weekAlreadyStartedTooltip: () => LocalizedString
		/**
		 * Alle Tage haben eine Priorität zugewiesen!
		 */
		allDaysAssigned: () => LocalizedString
		/**
		 * ✅ Alle Tage haben eine Priorität!
		 */
		allDaysHavePriority: () => LocalizedString
		/**
		 * Fertig
		 */
		done: () => LocalizedString
		/**
		 * 🎉 Feiertag
		 */
		publicHoliday: () => LocalizedString
		/**
		 * 🏖️ Urlaub
		 */
		vacationDay: () => LocalizedString
		/**
		 * 📋 Abwesend
		 */
		absent: () => LocalizedString
		/**
		 * Priorität
		 */
		priority: () => LocalizedString
		/**
		 * Prioritäten können nicht für Abwesenheitstage gesetzt werden
		 */
		priorityCannotBeSet: () => LocalizedString
		/**
		 * Diese Woche hat bereits begonnen und kann nicht mehr bearbeitet werden
		 */
		weekAlreadyStarted: () => LocalizedString
		/**
		 * Priorität {priority} tauschen (aktuell bei {day})
		 */
		swapPriority: (arg: { day: string, priority: number }) => LocalizedString
		/**
		 * Priorität {priority} wählen
		 */
		selectPriority: (arg: { priority: number }) => LocalizedString
		/**
		 * Tauschen mit {day}
		 */
		swapWith: (arg: { day: string }) => LocalizedString
		/**
		 * Priorität {priority}
		 */
		priorityNumber: (arg: { priority: number }) => LocalizedString
		/**
		 * Wird getauscht
		 */
		willBeSwapped: () => LocalizedString
		/**
		 * Gesperrt
		 */
		locked: () => LocalizedString
	}
	dashboard: {
		/**
		 * Dashboard
		 */
		title: () => LocalizedString
		/**
		 * Willkommen zurück!
		 */
		welcome: () => LocalizedString
		/**
		 * Willkommen zurück
		 */
		welcomeBack: () => LocalizedString
		/**
		 * Übersicht
		 */
		overview: () => LocalizedString
		/**
		 * Super! Alle Wochen für {month} sind priorisiert!
		 */
		allWeeksComplete: (arg: { month: string }) => LocalizedString
		/**
		 * Hier ist Ihre Übersicht für {month}
		 */
		overviewForMonth: (arg: { month: string }) => LocalizedString
		/**
		 * Monat auswählen:
		 */
		selectMonth: () => LocalizedString
		/**
		 * Lade Dashboard...
		 */
		loading: () => LocalizedString
		/**
		 * Statistiken
		 */
		statistics: () => LocalizedString
		/**
		 * Letzte Aktivität
		 */
		recentActivity: () => LocalizedString
		/**
		 * Keine Prioritäten gesetzt
		 */
		noPrioritiesSet: () => LocalizedString
		/**
		 * Prioritäten setzen
		 */
		setPriorities: () => LocalizedString
		/**
		 * Diesen Monat
		 */
		thisMonth: () => LocalizedString
		/**
		 * Diese Woche
		 */
		thisWeek: () => LocalizedString
		/**
		 * Heute
		 */
		today: () => LocalizedString
		/**
		 * Kommender Urlaub
		 */
		upcomingVacation: () => LocalizedString
		/**
		 * Kein kommender Urlaub
		 */
		noUpcomingVacation: () => LocalizedString
		/**
		 * Fortschritt
		 */
		progress: () => LocalizedString
		/**
		 * Fokus-Tag
		 */
		focusDay: () => LocalizedString
		/**
		 * Entspannter Tag
		 */
		relaxedDay: () => LocalizedString
		/**
		 * Oft mit hoher Priorität (4-5)
		 */
		oftenHighPriority: () => LocalizedString
		/**
		 * Oft mit niedriger Priorität (1-2)
		 */
		oftenLowPriority: () => LocalizedString
		/**
		 * Keine Daten
		 */
		noData: () => LocalizedString
		/**
		 * {count} von {total} Tagen priorisiert
		 */
		daysPrioritized: (arg: { count: number, total: number }) => LocalizedString
		/**
		 * Wochenübersicht - {month}
		 */
		weekOverview: (arg: { month: string }) => LocalizedString
		/**
		 * Woche
		 */
		week: () => LocalizedString
		/**
		 * Vollständig
		 */
		complete: () => LocalizedString
		/**
		 * In Bearbeitung
		 */
		inProgress: () => LocalizedString
		/**
		 * Nächste zu bearbeitende Woche: Woche {weekNumber}
		 */
		nextWeekToWorkOn: (arg: { weekNumber: number }) => LocalizedString
		/**
		 * Jetzt bearbeiten →
		 */
		editNow: () => LocalizedString
		/**
		 * Account-Verwaltung
		 */
		accountManagement: () => LocalizedString
		/**
		 * Passwort ändern, Gespeicherte Daten einsehen, Account löschen
		 */
		accountManagementDesc: () => LocalizedString
		/**
		 * Account verwalten →
		 */
		manageAccount: () => LocalizedString
	}
	account: {
		/**
		 * Konto
		 */
		title: () => LocalizedString
		/**
		 * Einstellungen
		 */
		settings: () => LocalizedString
		/**
		 * Profil
		 */
		profile: () => LocalizedString
		/**
		 * Sicherheit
		 */
		security: () => LocalizedString
		/**
		 * Einstellungen
		 */
		preferences: () => LocalizedString
		/**
		 * Sprache
		 */
		language: () => LocalizedString
		/**
		 * Sprache auswählen
		 */
		selectLanguage: () => LocalizedString
		/**
		 * Passwort ändern
		 */
		changePassword: () => LocalizedString
		/**
		 * Aktuelles Passwort
		 */
		currentPassword: () => LocalizedString
		/**
		 * Neues Passwort
		 */
		newPassword: () => LocalizedString
		/**
		 * Neues Passwort bestätigen
		 */
		confirmNewPassword: () => LocalizedString
		/**
		 * Profil aktualisieren
		 */
		updateProfile: () => LocalizedString
		/**
		 * Konto löschen
		 */
		deleteAccount: () => LocalizedString
		/**
		 * Möchten Sie Ihr Konto wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.
		 */
		deleteAccountConfirm: () => LocalizedString
		/**
		 * Account-Verwaltung
		 */
		accountManagement: () => LocalizedString
		/**
		 * Account-Informationen
		 */
		accountInfo: () => LocalizedString
		/**
		 * Username
		 */
		username: () => LocalizedString
		/**
		 * Nicht verfügbar
		 */
		notAvailable: () => LocalizedString
		/**
		 * Account erstellt
		 */
		accountCreated: () => LocalizedString
		/**
		 * Letzte Anmeldung
		 */
		lastLogin: () => LocalizedString
		/**
		 * Account-Status
		 */
		accountStatus: () => LocalizedString
		/**
		 * Aktiv
		 */
		active: () => LocalizedString
		/**
		 * 🔐 Passwort ändern
		 */
		changePasswordSection: () => LocalizedString
		/**
		 * Aktuelles Passwort eingeben
		 */
		currentPasswordPlaceholder: () => LocalizedString
		/**
		 * Neues Passwort eingeben
		 */
		newPasswordPlaceholder: () => LocalizedString
		/**
		 * Neues Passwort wiederholen
		 */
		confirmPasswordPlaceholder: () => LocalizedString
		/**
		 * Passwörter anzeigen
		 */
		showPasswords: () => LocalizedString
		/**
		 * Wird geändert...
		 */
		changing: () => LocalizedString
		/**
		 * Schwach
		 */
		passwordWeak: () => LocalizedString
		/**
		 * Mittel
		 */
		passwordMedium: () => LocalizedString
		/**
		 * Gut
		 */
		passwordGood: () => LocalizedString
		/**
		 * Stark
		 */
		passwordStrong: () => LocalizedString
		/**
		 * Bitte füllen Sie alle Felder aus
		 */
		errorAllFieldsRequired: () => LocalizedString
		/**
		 * Die neuen Passwörter stimmen nicht überein
		 */
		errorPasswordMismatch: () => LocalizedString
		/**
		 * Das neue Passwort muss sich vom aktuellen unterscheiden
		 */
		errorPasswordMustDiffer: () => LocalizedString
		/**
		 * Passwort erfolgreich geändert
		 */
		successPasswordChanged: () => LocalizedString
		/**
		 * Fehler beim Ändern des Passworts
		 */
		errorChangingPassword: () => LocalizedString
		/**
		 * 📊 Datenverwaltung (DSGVO)
		 */
		dataManagement: () => LocalizedString
		/**
		 * Gemäß der Datenschutz-Grundverordnung haben Sie das Recht auf Auskunft, Berichtigung und Löschung Ihrer personenbezogenen Daten.
		 */
		gdprNotice: () => LocalizedString
		/**
		 * Gespeicherte Daten einsehen
		 */
		viewStoredData: () => LocalizedString
		/**
		 * Daten exportieren
		 */
		exportData: () => LocalizedString
		/**
		 * Fehler beim Abrufen der Daten: {error}
		 */
		errorFetchingData: (arg: { error: string }) => LocalizedString
		/**
		 * Daten erfolgreich exportiert
		 */
		successDataExported: () => LocalizedString
		/**
		 * Fehler beim Exportieren: {error}
		 */
		errorExportingData: (arg: { error: string }) => LocalizedString
		/**
		 * ⚠️ Gefahrenzone
		 */
		dangerZone: () => LocalizedString
		/**
		 * Das Löschen Ihres Accounts ist unwiderruflich. Alle Ihre Daten werden permanent gelöscht.
		 */
		deleteWarning: () => LocalizedString
		/**
		 * Account löschen
		 */
		deleteAccountButton: () => LocalizedString
		/**
		 * ⚠️ Account dauerhaft löschen
		 */
		deleteConfirmTitle: () => LocalizedString
		/**
		 * Diese Aktion ist unwiderruflich! Folgende Daten werden gelöscht:
		 */
		deleteIrreversible: () => LocalizedString
		/**
		 * Ihr Benutzerkonto und alle Anmeldedaten
		 */
		deleteItemAccount: () => LocalizedString
		/**
		 * Alle gespeicherten Prioritäten
		 */
		deleteItemPriorities: () => LocalizedString
		/**
		 * Nach der Löschung erhalten Sie einen Löschbericht als Nachweis gemäß DSGVO Art. 17.
		 */
		deletionReport: () => LocalizedString
		/**
		 * Geben Sie LÖSCHEN zur Bestätigung ein:
		 */
		deleteConfirmPrompt: () => LocalizedString
		/**
		 * LÖSCHEN
		 */
		deleteConfirmText: () => LocalizedString
		/**
		 * Lösche Account...
		 */
		deleting: () => LocalizedString
		/**
		 * Account endgültig löschen
		 */
		deleteAccountFinal: () => LocalizedString
		/**
		 * Abbrechen
		 */
		cancel: () => LocalizedString
		/**
		 * Bitte geben Sie "LÖSCHEN" zur Bestätigung ein
		 */
		errorDeleteConfirm: () => LocalizedString
		/**
		 * Fehler beim Löschen: {error}
		 */
		errorDeleting: (arg: { error: string }) => LocalizedString
		/**
		 * Account wurde gelöscht. Löschbericht wurde heruntergeladen.
		 */
		successDeleted: () => LocalizedString
		/**
		 * Ihr Account wurde vollständig gelöscht gemäß DSGVO Art. 17
		 */
		deletionCompleteMessage: () => LocalizedString
		/**
		 * Ihre gespeicherten Daten
		 */
		yourStoredData: () => LocalizedString
		/**
		 * Schließen
		 */
		close: () => LocalizedString
		/**
		 * ℹ️ Dies ist eine vollständige Kopie aller Daten, die wir über Sie speichern (DSGVO Art. 15)
		 */
		gdprDataInfo: () => LocalizedString
		/**
		 * Als JSON exportieren
		 */
		exportAsJson: () => LocalizedString
		/**
		 * Sitzung abgelaufen
		 */
		sessionExpiredTitle: () => LocalizedString
		/**
		 * Ihre Sitzung ist abgelaufen. Sie werden zur Anmeldung weitergeleitet...
		 */
		sessionExpiredMessage: () => LocalizedString
		/**
		 * Sitzung abgelaufen. Bitte melden Sie sich erneut an.
		 */
		errorSessionExpired: () => LocalizedString
		/**
		 * Fehler beim Laden der Kontoinformationen
		 */
		errorLoadingAccountInfo: () => LocalizedString
		/**
		 * Lade Account...
		 */
		loadingAccount: () => LocalizedString
	}
	vacation: {
		/**
		 * Urlaub
		 */
		title: () => LocalizedString
		/**
		 * Urlaub hinzufügen
		 */
		addVacation: () => LocalizedString
		/**
		 * Urlaub bearbeiten
		 */
		editVacation: () => LocalizedString
		/**
		 * Urlaub löschen
		 */
		deleteVacation: () => LocalizedString
		/**
		 * Startdatum
		 */
		startDate: () => LocalizedString
		/**
		 * Enddatum
		 */
		endDate: () => LocalizedString
		/**
		 * Tage
		 */
		days: () => LocalizedString
		/**
		 * Gesamte Urlaubstage
		 */
		totalVacationDays: () => LocalizedString
		/**
		 * Verbleibende Urlaubstage
		 */
		remainingVacationDays: () => LocalizedString
		/**
		 * Genutzte Urlaubstage
		 */
		usedVacationDays: () => LocalizedString
	}
	notifications: {
		/**
		 * Benachrichtigungen
		 */
		title: () => LocalizedString
		/**
		 * Keine Benachrichtigungen
		 */
		noNotifications: () => LocalizedString
		/**
		 * Als gelesen markieren
		 */
		markAsRead: () => LocalizedString
		/**
		 * Alle als gelesen markieren
		 */
		markAllAsRead: () => LocalizedString
		/**
		 * Alle löschen
		 */
		clearAll: () => LocalizedString
	}
	errors: {
		/**
		 * Ein Fehler ist aufgetreten
		 */
		general: () => LocalizedString
		/**
		 * Netzwerkfehler
		 */
		networkError: () => LocalizedString
		/**
		 * Serverfehler
		 */
		serverError: () => LocalizedString
		/**
		 * Nicht gefunden
		 */
		notFound: () => LocalizedString
		/**
		 * Nicht autorisiert
		 */
		unauthorized: () => LocalizedString
		/**
		 * Verboten
		 */
		forbidden: () => LocalizedString
		/**
		 * Validierungsfehler
		 */
		validationError: () => LocalizedString
		/**
		 * Sitzung abgelaufen
		 */
		sessionExpired: () => LocalizedString
		/**
		 * Anmeldung fehlgeschlagen
		 */
		loginFailed: () => LocalizedString
		/**
		 * Registrierung fehlgeschlagen
		 */
		registrationFailed: () => LocalizedString
		/**
		 * Ungültige Anmeldedaten
		 */
		invalidCredentials: () => LocalizedString
		/**
		 * Benutzer existiert bereits
		 */
		userAlreadyExists: () => LocalizedString
		/**
		 * Passwort zu kurz
		 */
		passwordTooShort: () => LocalizedString
		/**
		 * Passwörter stimmen nicht überein
		 */
		passwordMismatch: () => LocalizedString
		/**
		 * Dieses Feld ist erforderlich
		 */
		requiredField: () => LocalizedString
		/**
		 * Ungültige E-Mail-Adresse
		 */
		invalidEmail: () => LocalizedString
		/**
		 * Ungültiges Datum
		 */
		invalidDate: () => LocalizedString
		/**
		 * Bitte versuchen Sie es erneut
		 */
		tryAgain: () => LocalizedString
	}
	success: {
		/**
		 * Erfolgreich gespeichert
		 */
		saved: () => LocalizedString
		/**
		 * Erfolgreich aktualisiert
		 */
		updated: () => LocalizedString
		/**
		 * Erfolgreich gelöscht
		 */
		deleted: () => LocalizedString
		/**
		 * Erfolgreich erstellt
		 */
		created: () => LocalizedString
		/**
		 * Erfolgreich angemeldet
		 */
		loginSuccess: () => LocalizedString
		/**
		 * Erfolgreich abgemeldet
		 */
		logoutSuccess: () => LocalizedString
		/**
		 * Erfolgreich registriert
		 */
		registrationSuccess: () => LocalizedString
		/**
		 * Passwort erfolgreich geändert
		 */
		passwordChanged: () => LocalizedString
		/**
		 * Profil erfolgreich aktualisiert
		 */
		profileUpdated: () => LocalizedString
	}
	admin: {
		/**
		 * Admin
		 */
		title: () => LocalizedString
		/**
		 * Admin Dashboard
		 */
		dashboard: () => LocalizedString
	}
}

export type Formatters = {}
